### PR TITLE
Add MANAGE_GUILD permission to bot invite link

### PR DESCRIPTION
**Pull request by Devidxyz**
Needed to list existing invites in a server.
Related discussion: https://discord.com/channels/697041998728659035/1225061886513643520/1237750831454097500

### CODE REVIEW

**Review by BrickheadJohnny — COMMENTED** [review]
The changes look fine, but I think we should also return this permission on the `/permissions` endpoint & check it in the `DiscordBotPermissionsChecker` component. What do you think? If we'll do it in another PR, you can merge this one! ✅

**Comment by Devidxyz** [comment]
> The changes look fine, but I think we should also return this permission on the `/permissions` endpoint & check it in the `DiscordBotPermissionsChecker` component. What do you think? If we'll do it in another PR, you can merge this one! ✅

Honestly I never thought there's a useful suggestion for a 9 character PR, but yes, absolutely! Can I ask you a little favor to do this change for me? 👉🏻👈🏻

**Comment by BrickheadJohnny** [comment]
> > The changes look fine, but I think we should also return this permission on the `/permissions` endpoint & check it in the `DiscordBotPermissionsChecker` component. What do you think? If we'll do it in another PR, you can merge this one! ✅
> 
> Honestly I never thought there's a useful suggestion for a 9 character PR, but yes, absolutely! Can I ask you a little favor to do this change for me? 👉🏻👈🏻

Sure, it's quite simple on the frontend, added it quickly, should I do it on the backend too, or someone from the core team will handle it? 👀

**Comment by Devidxyz** [comment]
> > > The changes look fine, but I think we should also return this permission on the `/permissions` endpoint & check it in the `DiscordBotPermissionsChecker` component. What do you think? If we'll do it in another PR, you can merge this one! ✅
> > 
> > 
> > Honestly I never thought there's a useful suggestion for a 9 character PR, but yes, absolutely! Can I ask you a little favor to do this change for me? 👉🏻👈🏻
> 
> Sure, it's quite simple on the frontend, added it quickly, should I do it on the backend too, or someone from the core team will handle it? 👀

Oh, I haven't realized a BE change is needed, I will do it later today, thx.

**Comment by Devidxyz** [comment]
@BrickheadJohnny MANAGE_GUILD is now live in https://api.guild.xyz/v1/discord/permissions/996020077864423464

**Review by BrickheadJohnny — APPROVED** [review]

**Pull request merged**
